language: go
go_import_path: github.com/cloudflare/cloudflare-ingress-controller
go:
  - 1.11.x

sudo: false
install:
  - go get -u github.com/golang/dep/cmd/dep && dep ensure -vendor-only -v

script:
  - make check

notifications:
  email:
    recipients:
    - malberts@cloudflare.com
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)